// Mocks generated by Mockito 5.4.6 from annotations
// in caffeine_tracker/test/features/menu/domain/usecases/caffeine_record_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:caffeine_tracker/core/db/repositories/local_db_repository.dart'
    as _i7;
import 'package:caffeine_tracker/features/menu/data/models/caffeine_model.dart'
    as _i6;
import 'package:caffeine_tracker/features/menu/data/repositories/record_repository.dart'
    as _i2;
import 'package:caffeine_tracker/features/report/data/models/report_model.dart'
    as _i4;
import 'package:caffeine_tracker/features/report/data/models/report_with_drink_model.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [RecordRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockRecordRepository extends _i1.Mock implements _i2.RecordRepository {
  MockRecordRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<int> addRecord(_i4.DrinkRecordModel? product) =>
      (super.noSuchMethod(
            Invocation.method(#addRecord, [product]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<List<_i4.DrinkRecordModel>> getRecords() =>
      (super.noSuchMethod(
            Invocation.method(#getRecords, []),
            returnValue: _i3.Future<List<_i4.DrinkRecordModel>>.value(
              <_i4.DrinkRecordModel>[],
            ),
          )
          as _i3.Future<List<_i4.DrinkRecordModel>>);

  @override
  _i3.Future<List<_i4.DrinkRecordModel>> getTodayRecords() =>
      (super.noSuchMethod(
            Invocation.method(#getTodayRecords, []),
            returnValue: _i3.Future<List<_i4.DrinkRecordModel>>.value(
              <_i4.DrinkRecordModel>[],
            ),
          )
          as _i3.Future<List<_i4.DrinkRecordModel>>);

  @override
  _i3.Future<List<_i5.DrinkRecordWithItem>> getRecordsByRange({
    required DateTime? from,
    required DateTime? to,
    _i2.OrderBy? orderBy = _i2.OrderBy.asc,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getRecordsByRange, [], {
              #from: from,
              #to: to,
              #orderBy: orderBy,
            }),
            returnValue: _i3.Future<List<_i5.DrinkRecordWithItem>>.value(
              <_i5.DrinkRecordWithItem>[],
            ),
          )
          as _i3.Future<List<_i5.DrinkRecordWithItem>>);

  @override
  _i3.Future<List<_i5.DrinkRecordWithItem>> getRecordsWithItem() =>
      (super.noSuchMethod(
            Invocation.method(#getRecordsWithItem, []),
            returnValue: _i3.Future<List<_i5.DrinkRecordWithItem>>.value(
              <_i5.DrinkRecordWithItem>[],
            ),
          )
          as _i3.Future<List<_i5.DrinkRecordWithItem>>);

  @override
  _i3.Future<_i6.CaffeineItemModel?> getItemById({
    required bool? isCustom,
    required int? id,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getItemById, [], {#isCustom: isCustom, #id: id}),
            returnValue: _i3.Future<_i6.CaffeineItemModel?>.value(),
          )
          as _i3.Future<_i6.CaffeineItemModel?>);

  @override
  _i3.Future<void> deleteRecord(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRecord, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [CaffeineItemRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCaffeineItemRepository extends _i1.Mock
    implements _i7.CaffeineItemRepository {
  MockCaffeineItemRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i6.CaffeineItemModel>> getAllItems() =>
      (super.noSuchMethod(
            Invocation.method(#getAllItems, []),
            returnValue: _i3.Future<List<_i6.CaffeineItemModel>>.value(
              <_i6.CaffeineItemModel>[],
            ),
          )
          as _i3.Future<List<_i6.CaffeineItemModel>>);

  @override
  _i3.Future<List<_i6.CaffeineItemModel>> getOfficialItems() =>
      (super.noSuchMethod(
            Invocation.method(#getOfficialItems, []),
            returnValue: _i3.Future<List<_i6.CaffeineItemModel>>.value(
              <_i6.CaffeineItemModel>[],
            ),
          )
          as _i3.Future<List<_i6.CaffeineItemModel>>);

  @override
  _i3.Future<List<_i6.CaffeineItemModel>> getCustomItems() =>
      (super.noSuchMethod(
            Invocation.method(#getCustomItems, []),
            returnValue: _i3.Future<List<_i6.CaffeineItemModel>>.value(
              <_i6.CaffeineItemModel>[],
            ),
          )
          as _i3.Future<List<_i6.CaffeineItemModel>>);

  @override
  _i3.Future<List<_i6.CaffeineItemModel>> searchItems(
    String? keyword, {
    _i6.CaffeineCategory? category,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchItems, [keyword], {#category: category}),
            returnValue: _i3.Future<List<_i6.CaffeineItemModel>>.value(
              <_i6.CaffeineItemModel>[],
            ),
          )
          as _i3.Future<List<_i6.CaffeineItemModel>>);

  @override
  _i3.Future<List<_i6.CaffeineItemModel>> getItemsByHits() =>
      (super.noSuchMethod(
            Invocation.method(#getItemsByHits, []),
            returnValue: _i3.Future<List<_i6.CaffeineItemModel>>.value(
              <_i6.CaffeineItemModel>[],
            ),
          )
          as _i3.Future<List<_i6.CaffeineItemModel>>);

  @override
  _i3.Future<_i6.CaffeineItemModel?> getItemById({
    required bool? isCustom,
    required int? id,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getItemById, [], {#isCustom: isCustom, #id: id}),
            returnValue: _i3.Future<_i6.CaffeineItemModel?>.value(),
          )
          as _i3.Future<_i6.CaffeineItemModel?>);

  @override
  _i3.Future<int> addCustomItem(_i6.CaffeineItemModel? item) =>
      (super.noSuchMethod(
            Invocation.method(#addCustomItem, [item]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<void> incrementHits(int? id, bool? isCustom) =>
      (super.noSuchMethod(
            Invocation.method(#incrementHits, [id, isCustom]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<int> deleteCustomItem(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteCustomItem, [id]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<int> deleteAllDatas() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAllDatas, []),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);
}
